import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { MetadataRoute } from 'next/server';

interface Route {
  path: string;
  title: string;
}

const routes: Route[] = [
  { path: '/products', title: 'Products' },
  // Add more routes as needed from project spec
];

export default function Header() {
  const router = useRouter();
  const projectSpec = {
    appName: "Product Showcase",
    // ...rest of project spec (not used in this component)
  };

  return (
    <header className="bg-gray-800 text-white p-4">
      <nav className="container mx-auto flex justify-between items-center">
        <div>
          <Link href="/" className="text-2xl font-bold">{projectSpec.appName}</Link>
        </div>
        <ul className="flex space-x-4">
          {routes.map((route) => (
            <li key={route.path}>
              <Link
                href={route.path}
                className={`px-4 py-2 rounded-md ${router.pathname === route.path ? 'bg-gray-600' : 'hover:bg-gray-600'}`}
              >
                {route.title}
              </Link>
            </li>
          ))}
        </ul>
        <button className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
          CTA
        </button>
      </nav>
    </header>
  );
}

export const metadata: MetadataRoute = {
  title: 'Product Showcase',
  description: 'Generated by create next app',
};