import "./globals.css";
export const metadata = { title: "App", description: "Generated by autoapp" };
export default function RootLayout({ children }:{children: React.ReactNode}) {
  return (<html lang="en"><body>{children}</body></html>);
}